apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: datadog-operator
  template:
    metadata:
      labels:
        name: datadog-operator
    spec:
      serviceAccountName: datadog-operator
      containers:
        - name: datadog-operator
          image: datadog/operator:latest
          command:
          - datadog-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "datadog-operator"
