datadog-operator:
  toolVersion: eks-addon
  datadogCRDs:
    crds:
      datadogMonitors: false
  image:
    repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/datadog/operator
    tag: 1.22.0
  operatorMetricsEnabled: false
