name: yaml-mapper
on:
  pull_request:
    paths:
      - "cmd/yaml-mapper/**"
  push:
    paths:
      - "cmd/yaml-mapper/**"
# Permission forced by repo-level setting; only elevate on job-level
permissions:
  contents: read
  # packages: read
env:
  PROJECTNAME: "datadog-operator"
  GO_VERSION: 1.25.3
jobs:
  yaml-mapper-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version: ${{ env.GO_VERSION }}
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: run yaml-mapper unit tests
        run: |
          make yaml-mapper-tests
